#!/usr/bin/env ruby
# encoding: utf-8
#
#

system('clear')

puts
puts "Schlafphasenrechner"
puts

print "Bitte geben Sie die Zeit ein, wann Sie schlafen gehen wollen (1:30): "
ts = gets.strip.match(/^(\d{1,2}):(\d{1,2})$/mi)
th = ts[1].to_i || 0
tm = ts[2].to_i || 0

raise "Minuten müssen zwischen 0 und 59 liegen." unless (0..59).include? tm
raise "Stunden müssen zwischen 0 und 23 liegen." unless (0..23).include? th

puts
puts "Zeit in der Sie schlafen gehen wollen: #{ Time.new(2013,04,17,th,tm).strftime('%H:%M') }"
puts
print "Bitte geben Sie ihre Schlafphase in Minuten an (oft 90): "
schlafphase = gets.strip.to_i

raise "Schlafphase sollte zwischen 60 und 120 liegen" unless (60..120).include? schlafphase

def s_calc(sp, p, h, m)
    t = Time.now
    t = Time.new(t.year, t.hour, t.day, h, m)
    t + sp*60*p
end
puts
7.times do |i|
    s = s_calc(schlafphase, i, th, tm)
    puts "P#{ i }: #{ s.strftime('%H:%M') } - #{ (s + 40*60).strftime('%H:%M') }"
end
